### ISSUE TITLE
Client

### ISSUE THREAD

**Issue by ghost** [nwestfall/SocketClient#1]
@nwestfall Nice app, do you have a server side listening for incoming data file? If you do where can I find the code?

**Comment by nwestfall** [comment]
@di48l069 I do, but it's only for private use currently.  This client was built to test basic connections with that server side implementation.  If it is something you are interested in, I can add a simple version of it to use with this client.

**Comment by ghost** [comment]
Yes please do add me im extreamly interested.

**Comment by nwestfall** [comment]
@di48l069 take a look for the server [here](https://github.com/nwestfall/SocketServer)
